"""mvp schema

Revision ID: 990abeffeae4
Revises: 52ee4f3e419f
Create Date: 2025-11-26 15:29:56.047977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '990abeffeae4'
down_revision: Union[str, Sequence[str], None] = '52ee4f3e419f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charge_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charge_point_id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('ocpp_transaction_id', sa.String(), nullable=True),
    sa.Column('user_tag', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('energy_kwh', sa.Float(), nullable=True),
    sa.Column('cost_huf', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_charge_sessions_id'), 'charge_sessions', ['id'], unique=False)
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_connectors_id'), table_name='connectors')
    op.drop_table('connectors')
    op.alter_column('charge_points', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.drop_constraint(op.f('charge_points_ocpp_id_key'), 'charge_points', type_='unique')
    op.create_index(op.f('ix_charge_points_ocpp_id'), 'charge_points', ['ocpp_id'], unique=True)
    op.drop_constraint(op.f('charge_points_organization_id_fkey'), 'charge_points', type_='foreignkey')
    op.drop_constraint(op.f('charge_points_location_id_fkey'), 'charge_points', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('charge_points_location_id_fkey'), 'charge_points', 'locations', ['location_id'], ['id'])
    op.create_foreign_key(op.f('charge_points_organization_id_fkey'), 'charge_points', 'organizations', ['organization_id'], ['id'])
    op.drop_index(op.f('ix_charge_points_ocpp_id'), table_name='charge_points')
    op.create_unique_constraint(op.f('charge_points_ocpp_id_key'), 'charge_points', ['ocpp_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('charge_points', 'status',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.create_table('connectors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('charge_point_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('connector_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_kw', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('last_status_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['charge_point_id'], ['charge_points.id'], name=op.f('connectors_charge_point_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('connectors_pkey'))
    )
    op.create_index(op.f('ix_connectors_id'), 'connectors', ['id'], unique=False)
    op.create_table('organizations',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('organizations_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='organizations_pkey'),
    sa.UniqueConstraint('name', name='organizations_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('slug', name='organizations_slug_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address_text', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.NUMERIC(precision=9, scale=6), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('locations_organization_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('locations_pkey'))
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.drop_index(op.f('ix_charge_sessions_id'), table_name='charge_sessions')
    op.drop_table('charge_sessions')
    # ### end Alembic commands ###
